### ISSUE TITLE
성향분석 개발

### ISSUE THREAD

**Issue by hsw0914** [UHSSPO/Prj-SPO#62]

**Comment by KurtDev599** [comment]
1. 고객님의 금융상품 투자에 대한 지식수준:

- 매우 낮은 수준: 0점
- 낮은 수준: 3점
- 높은 수준: 7점
- 매우 높은 수준: 10점

2. 고객님의 수입원:
- 현재 수입 유지 또는 증가 예상: 10점
- 현재 수입 감소 또는 불안정 예상: 7점
- 현재 수입 없음, 연금 주 수입: 3점

3. 연간 소득:
- 2천만원 이하: 0점
- 5천만원 이하: 3점
- 1억원 이하: 7점
- 1억원 초과: 10점

4. 투자경험:
- 안정형 상품에 투자 경험: 0점
- 위험 중립형 상품에 투자 경험: 3점
- 적극투자형 상품에 투자 경험: 7점
- 공격투자형 상품에 투자 경험: 10점

5. 투자상품 비중:
- 10% 이하: 0점
- 15% 이하: 3점
- 20% 이하: 7점
- 25% 초과: 10점

6. 파생상품 투자 경험:
- 투자 경험 없음: 0점
- 1년 이하: 3점
- 3년 이하: 7점
- 3년 초과: 10점

7. 투자기대 수익과 손실 감내 수준:
- 투자원금 보존 우선: 0점
- 10% 미만 손실 감내: 3점
- 20% 미만 손실 감내: 7점
- 위험 감수 가능: 10점

8. 금융투자상품 가입 목적:
- 사용 예정 자금 운용: 0점
- 목적 자금 마련: 3점
- 노후 자금 마련: 7점
- 자산 증식 우선: 10점

9. 투자기간:
- 1년 미만: 0점
- 1년 이상: 3점
- 2년 이상: 7점
- 3년 이상: 10점
-------



- 안정형: 0 ~ 20점
- 안정추구형: 21 ~ 40점
- 위험중립형: 41 ~ 60점
- 적극투자형: 61 ~ 80점
- 공격투자형: 81 ~ 100점

고객님의 성실한 답변에 감사드리며, 답변해 주신 본 질문지에 기초해 고객님께 적합한 상품을 제공하도록 노력하겠습니다. 본 질문지에서 수집된 개인정보는 고객님께 적합한 상품을 제공하기 위한 기초자료만으로 활용할 예정이며 SPO에 의하여 기밀로 보호될 것을 약속드립니다. 다음 화면에서 제공되는 투자자성향 분석 결과는 고객님께서 제공하신 정보를 바탕으로 분석되었으며, 거래목적, 계약기간·기대이익·기대손실을 고려한 위험에 대한 태도, 금융상품에 대한 이해도, 재산상황, 투자성상품의 취득·처분 경험, 연령 등에 비추어 적합한 상품을 추천 드립니다.
본인은 투자위험에 대한 본인의 성향이 올바르게 선택되어 있음을 확인합니다.

**Comment by KurtDev599** [comment]
05 = 찐한빨강
04 = 주황
03 = 노랑
02 = 파랑
01 = 초록
